apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "demo-sso-client.fullname" . }}
  labels:
    {{- include "demo-sso-client.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "demo-sso-client.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "demo-sso-client.selectorLabels" . | nindent 8 }}
    spec:
      imagePullSecrets:
        - name: {{ include "demo-sso-client.imagePullSecret" . }}
      serviceAccountName: {{ include "demo-sso-client.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ include "demo-sso-client.imageName" . }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ include "demo-sso-client.imagePullPolicy" . }}
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: prod
          ports:
            - name: http
              containerPort: 4904
              protocol: TCP
          livenessProbe:
            tcpSocket:
              port: 4904
          readinessProbe:
            tcpSocket:
              port: 4904
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
